### ISSUE TITLE
Pseudo Funcionalidad

### ISSUE THREAD

**Issue by ChristianRoig** [ChristianRoig/ang-7i-skeleton#21]
Por default el usuario es Florencia (fm/fm), pero te podes loguear con (fq/qf) = Fabian Quinteros y (sf/sf) Sandra Frassoni. Cambia nombre y avatar en Nav Bar
(si se puede Cristina Estrada, face)

Nómina cambia contenido de la lista (6 listas distintas):
para Nomina/Card/Net/Hnos/Dtos/Suc. (ver consultas SQL)
si se marca el check se muestra columna de estado, sino email.

**Comment by gonzalezvictorjuan** [comment]
'nombre': 'Cristina Estrada',
        'nombre_corto': 'Cristina Estrada',
        'telefono': '(0249)438-7687',
        'correo': 'cristina.estrada@gmail.com',
        'img': 'assets/images/perfil/flor.jpg',
        'address': 'Av. Colon 1266, Mar del Plata',
        'infoLaboral': {
            'legajo': '4152',
            'puesto': 'Jefe de Sistemas',
            'LugarTrabajo': 'Mar del Plata',
        },
        'datosSistema': {
            'usuario': 'cristina.estrada',
            'perfiles': 'Supervisor, RRHH',
            'correoLaboral': 'cristina.estrada@favanet.com.ar',
            'telefonoLaboral': '(0223) 444-4999 int. 438',
        },
